Ласкаво просимо на наш урок, де ми зануримося у світ незмінних повторень та безмежних можливостей. Сьогодні ми візьмемо на збори потужний інструмент - цикли, які дозволять нам створити магію, повторювати дії і втілювати складні задачі у кілька простих кроків. Підготуйтеся до захоплюючої подорожі, де ви дізнаєтеся, як цікаві алгоритми розкривають величність повторення. Всі готові? Тоді почнемо цей урок з циклами, які роблять нас майстрами ітерацій!

**Зірковий трикутник**

На вхід програмі подається натуральне число n (n ≥ 2) – катет прямокутного рівнобедреного трикутника.

Напишіть програму, яка виводить зірковий трикутник відповідно до прикладу.

**Формат вхідних даних**

На вхід до програми подається одне натуральне число n (n ≥ 2).

**Формат вихідних даних**

Програма повинна вивести трикутник відповідно до умови завдання.

**Sample Input 1:**

3

**Sample Output 1:**

*

**

\***

**Sample Input 2:**

6

**Sample Output 2:**

*

**

\***

\****

\*****

\******

In [14]:
n = int(input("Введіть натуральне число n: "))

for i in range(1, n + 1):
    print('*' * i)

Введіть натуральне число n: 6
*
**
***
****
*****
******

**Таблиця множення**

Дано натуральне число n. Напишіть програму, яка виводить таблицю множення на n (від 1 до 10 включно).

**Формат вхідних даних**

На вхід до програми подається натуральне число.

**Формат вихідних даних**

Програма має вивести таблицю множення на введене число.

**Sample Input 1:**

5

**Sample Output 1:**

5 x 1 = 5

5 x 2 = 10

5 x 3 = 15

5 x 4 = 20

5 x 5 = 25

5 x 6 = 30

5 x 7 = 35

5 x 8 = 40

5 x 9 = 45

5 x 10 = 50

In [16]:
n = int(input("Введіть натуральне число n: "))

for i in range(1, 11):
    print(n, 'x', i, '=', n * i)

Введіть натуральне число n: 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

**Факторіал**

На вхід до програми подається натуральне число n. Напишіть програму, яка обчислює n! .

**Формат вхідних даних**

На вхід до програми подається натуральне число n (n≤12).

**Формат вихідних даних**

Програма повинна вивести однину відповідно до умови завдання.

**Примітка:** Добуток всіх натуральних чисел від 1 до n називається факторіалом числа n.

*n! = 1 ⋅ 2 ⋅ 3 ⋅ … ⋅ n**

**Sample Input 1:**

3

**Sample Output 1:**

6

**Sample Input 2:**

1

**Sample Output 2:**

1

**Sample Input 3:**

5

**Sample Output 3:**

120

In [37]:
n = int(input("Введіть натуральне число n: "))

factorial = 1
for i in range(1, n + 1):
    factorial *= i

print(str(n) + "!" + " =", factorial)

Введіть натуральне число n: 5
5! = 120

**Сума дільників**

На вхід до програми подається натуральне число n. Напишіть програму, яка обчислює суму всіх дільників.

**Формат вхідних даних**

На вхід до програми подається натуральне число n.

**Формат вихідних даних**

Програма повинна вивести число відповідно до умови завдання.


**Sample Input 1:**

10

**Sample Output 1:**

18

**Sample Input 2:**

50

**Sample Output 2:**

93

**Sample Input 3:**

3

**Sample Output 3:**

4

In [44]:
n = int(input("Введіть натуральне число n: "))

divisors_sum = 0

for i in range(1, n + 1):
    if n % i == 0:
        divisors_sum += i

print("Cума всіх дільників:", divisors_sum)

Введіть натуральне число n: 50
Cума всіх дільників: 93

**Дотримуйся правил**

На вхід до програми подається натуральне число n. Напишіть програму, яка виводить числа від 1 до n включно, за винятком:

- Чисел від 5 до 9 включно;
- Чисел від 17 до 37 включно;
- Чисел від 78 до 87 включно;

**Формат вхідних даних**

На вхід до програми подається натуральне число n.

**Формат вихідних даних**

Програма повинна вивести числа відповідно до умови завдання, кожне на окремому рядку.

**Примітка**. Використовуйте оператор continue.

**Sample Input 1:**

10

**Sample Output 1:**

1

2

3

4

10

**Sample Input 2:**

20

**Sample Output 2:**

1

2

3

4

10

11

12

13

14

15

16

In [48]:
n = int(input("Введіть натуральне число n: "))

for i in range(1, n + 1):
    if 5 <= i <= 9 or 17 <= i <= 37 or 78 <= i <= 87:
        continue
    print(i)

Введіть натуральне число n: 20
1
2
3
4
10
11
12
13
14
15
16

**Відьмаку заплатіть чеканою монетою**

Всім відомо, що відьмак здатний здолати будь-яких потвор, проте його послуги обійдуться недешево, до того ж відьмак не приймає купюри, він приймає лише карбовані монети. У світі відьмака є монети з номіналами 1, 5, 10, 25.

Напишіть програму, яка визначає яку мінімальну кількість карбованих монет потрібно заплатити відьмаку.

**Формат вхідних даних**

На вхід до програми подається одне натуральне число, ціна за послугу відьмака.

**Формат вихідних даних**

Програма має вивести мінімально можливу кількість карбованих монет для оплати.

**Sample Input 1**

49

**Sample Output 1**

7

**Sample Input 2**

1

**Sample Output 2**

1

**Sample Input 3**

5

**Sample Output 3**

1

In [51]:
price = int(input("Ціна за послугу відьмака: "))

coins = [25, 10, 5, 1]
count = 0

for coin in coins:
    count += price // coin
    price %= coin

print("Мінімальна можлива кількість карбованих монет для оплати:", count)

Ціна за послугу відьмака: 49
Мінімальна можлива кількість карбованих монет для оплати: 7